ChibiOS/RT: Delegate Threads
Delegate Threads
OS Library » Synchronization
Detailed Description
Typedefs
typedef msg_t(* delegate_veneer_t) (va_list *argsp)
Type of a delegate veneer function.
typedef msg_t(* delegate_fn0_t) (void)
Type of a delegate function with no parameters.
typedef msg_t(* delegate_fn1_t) (msg_t p1)
Type of a delegate function with one parameter.
typedef msg_t(* delegate_fn2_t) (msg_t p1, msg_t p2)
Type of a delegate function with two parameters.
typedef msg_t(* delegate_fn3_t) (msg_t p1, msg_t p2, msg_t p3)
Type of a delegate function with three parameters.
typedef msg_t(* delegate_fn4_t) (msg_t p1, msg_t p2, msg_t p3, msg_t p4)
Type of a delegate function with four parameters.
Functions
msg_t __ch_delegate_fn0 (va_list *argsp)
Veneer for functions with no parameters.
msg_t __ch_delegate_fn1 (va_list *argsp)
Veneer for functions with one parameter.
msg_t __ch_delegate_fn2 (va_list *argsp)
Veneer for functions with two parameters.
msg_t __ch_delegate_fn3 (va_list *argsp)
Veneer for functions with three parameters.
msg_t __ch_delegate_fn4 (va_list *argsp)
Veneer for functions with four parameters.
msg_t chDelegateCallVeneer (thread_t *tp, delegate_veneer_t veneer,...)
Triggers a function call on a delegate thread.
void chDelegateDispatch (void)
Call messages dispatching.
msg_t chDelegateDispatchTimeout (sysinterval_t timeout)
Call messages dispatching with timeout.
static msg_t chDelegateCallDirect0 (thread_t *tp, delegate_fn0_t func)
Direct call to a function with no parameters.
static msg_t chDelegateCallDirect1 (thread_t *tp, delegate_fn1_t func, msg_t p1)
Direct call to a function with one parameter.
static msg_t chDelegateCallDirect2 (thread_t *tp, delegate_fn2_t func, msg_t p1, msg_t p2)
Direct call to a function with two parameters.
static msg_t chDelegateCallDirect3 (thread_t *tp, delegate_fn3_t func, msg_t p1, msg_t p2, msg_t p3)
Direct call to a function with three parameters.
static msg_t chDelegateCallDirect4 (thread_t *tp, delegate_fn4_t func, msg_t p1, msg_t p2, msg_t p3, msg_t p4)
Direct call to a function with four parameters.
Typedef Documentation
delegate_veneer_t
typedef msg_t(* delegate_veneer_t) (va_list *argsp)
Type of a delegate veneer function.
Definition at line 60 of file chdelegates.h.
delegate_fn0_t
typedef msg_t(* delegate_fn0_t) (void)
Type of a delegate function with no parameters.
Definition at line 65 of file chdelegates.h.
delegate_fn1_t
typedef msg_t(* delegate_fn1_t) (msg_t p1)
Type of a delegate function with one parameter.
Definition at line 70 of file chdelegates.h.
delegate_fn2_t
typedef msg_t(* delegate_fn2_t) (msg_t p1, msg_t p2)
Type of a delegate function with two parameters.
Definition at line 75 of file chdelegates.h.
delegate_fn3_t
typedef msg_t(* delegate_fn3_t) (msg_t p1, msg_t p2, msg_t p3)
Type of a delegate function with three parameters.
Definition at line 80 of file chdelegates.h.
delegate_fn4_t
typedef msg_t(* delegate_fn4_t) (msg_t p1, msg_t p2, msg_t p3, msg_t p4)
Type of a delegate function with four parameters.
Definition at line 85 of file chdelegates.h.
Function Documentation
__ch_delegate_fn0()
msg_t __ch_delegate_fn0 (va_list * argsp)
Veneer for functions with no parameters.
Parameters
[in] argsp the list of arguments
Returns
The function return value.
Definition at line 88 of file chdelegates.c.
Referenced by chDelegateCallDirect0().
__ch_delegate_fn1()
msg_t __ch_delegate_fn1 (va_list * argsp)
Veneer for functions with one parameter.
Parameters
[in] argsp the list of arguments
Returns
The function return value.
Definition at line 99 of file chdelegates.c.
Referenced by chDelegateCallDirect1().
__ch_delegate_fn2()
msg_t __ch_delegate_fn2 (va_list * argsp)
Veneer for functions with two parameters.
Parameters
[in] argsp the list of arguments
Returns
The function return value.
Definition at line 111 of file chdelegates.c.
Referenced by chDelegateCallDirect2().
__ch_delegate_fn3()
msg_t __ch_delegate_fn3 (va_list * argsp)
Veneer for functions with three parameters.
Parameters
[in] argsp the list of arguments
Returns
The function return value.
Definition at line 124 of file chdelegates.c.
Referenced by chDelegateCallDirect3().
__ch_delegate_fn4()
msg_t __ch_delegate_fn4 (va_list * argsp)
Veneer for functions with four parameters.
Parameters
[in] argsp the list of arguments
Returns
The function return value.
Definition at line 138 of file chdelegates.c.
Referenced by chDelegateCallDirect4().
chDelegateCallVeneer()
msg_t chDelegateCallVeneer (thread_t * tp, delegate_veneer_t veneer, ...)
Triggers a function call on a delegate thread.
Note
The thread must be executing chDelegateDispatchTimeout() in order to have the functions called.
Parameters
[in] tp pointer to the delegate thread
[in] veneer pointer to the veneer function to be called
[in] ... variable number of parameters
Returns
The function return value casted to msg_t. It is garbage for functions returning void.
Definition at line 158 of file chdelegates.c.
References chMsgSend().
Referenced by chDelegateCallDirect0(), chDelegateCallDirect1(), chDelegateCallDirect2(), chDelegateCallDirect3(), and chDelegateCallDirect4().
chDelegateDispatch()
void chDelegateDispatch (void)
Call messages dispatching.
The function awaits for an incoming call messages and calls the specified functions, then it returns. In case multiple threads are sending messages then the requests are served in priority order.
Function Class:\n Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 190 of file chdelegates.c.
References chMsgGet(), chMsgRelease(), and chMsgWait().
chDelegateDispatchTimeout()
msg_t chDelegateDispatchTimeout (sysinterval_t timeout)
Call messages dispatching with timeout.
The function awaits for an incoming call messages and calls the specified functions, then it returns. In case multiple threads are sending messages then the requests are served in priority order.
Parameters
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The function outcome.
Return values
MSG_OK if a function has been called.
MSG_TIMEOUT if a timeout occurred.
Function Class:\n Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 219 of file chdelegates.c.
References chMsgGet(), chMsgRelease(), chMsgWaitTimeout(), MSG_OK, and MSG_TIMEOUT.
chDelegateCallDirect0()
static msg_t chDelegateCallDirect0 (thread_t * tp, delegate_fn0_t func) inline static
Direct call to a function with no parameters.
Note
The return value is assumed to be not larger than a data pointer type. If you need a portable function then use chDelegateCallVeneer() instead.
Parameters
[in] tp pointer to the delegate thread
[in] func pointer to the function to be called
Returns
The function return value as a msg_t.
Definition at line 124 of file chdelegates.h.
References __ch_delegate_fn0(), and chDelegateCallVeneer().
chDelegateCallDirect1()
static msg_t chDelegateCallDirect1 (thread_t * tp, delegate_fn1_t func, msg_t p1) inline static
Direct call to a function with one parameter.
Note
The return value and parameters are assumed to be not larger than a data pointer type. If you need a portable function then use chDelegateCallVeneer() instead.
Parameters
[in] tp pointer to the delegate thread
[in] func pointer to the function to be called
[in] p1 parameter 1 passed as a msg_t
Returns
The function return value as a msg_t.
Definition at line 140 of file chdelegates.h.
References __ch_delegate_fn1(), and chDelegateCallVeneer().
chDelegateCallDirect2()
static msg_t chDelegateCallDirect2 (thread_t * tp, delegate_fn2_t func, msg_t p1, msg_t p2) inline static
Direct call to a function with two parameters.
Note
The return value and parameters are assumed to be not larger than a data pointer type. If you need a portable function then use chDelegateCallVeneer() instead.
Parameters
[in] tp pointer to the delegate thread
[in] func pointer to the function to be called
[in] p1 parameter 1 passed as a msg_t
[in] p2 parameter 2 passed as a msg_t
Returns
The function return value as a msg_t.
Definition at line 158 of file chdelegates.h.
References __ch_delegate_fn2(), and chDelegateCallVeneer().
chDelegateCallDirect3()
static msg_t chDelegateCallDirect3 (thread_t * tp, delegate_fn3_t func, msg_t p1, msg_t p2, msg_t p3) inline static
Direct call to a function with three parameters.
Note
The return value and parameters are assumed to be not larger than a data pointer type. If you need a portable function then use chDelegateCallVeneer() instead.
Parameters
[in] tp pointer to the delegate thread
[in] func pointer to the function to be called
[in] p1 parameter 1 passed as a msg_t
[in] p2 parameter 2 passed as a msg_t
[in] p3 parameter 3 passed as a msg_t
Returns
The function return value as a msg_t.
Definition at line 177 of file chdelegates.h.
References __ch_delegate_fn3(), and chDelegateCallVeneer().
chDelegateCallDirect4()
static msg_t chDelegateCallDirect4 (thread_t * tp, delegate_fn4_t func, msg_t p1, msg_t p2, msg_t p3, msg_t p4) inline static
Direct call to a function with four parameters.
Note
The return value and parameters are assumed to be not larger than a data pointer type. If you need a portable function then use chDelegateCallVeneer() instead.
Parameters
[in] tp pointer to the delegate thread
[in] func pointer to the function to be called
[in] p1 parameter 1 passed as a msg_t
[in] p2 parameter 2 passed as a msg_t
[in] p3 parameter 3 passed as a msg_t
[in] p4 parameter 4 passed as a msg_t
Returns
The function return value as a msg_t.
Definition at line 197 of file chdelegates.h.
References __ch_delegate_fn4(), and chDelegateCallVeneer().